#!/usr/bin/env bash
# SealyJ
# version 0.2
today=$(date +"%m_%d_%Y")
temp_storage=~/../usr/tmp
backup_location=~/storage/shared/tel/backup

check_folders(){
if [ ! -d $temp_storage ] ; then
	mkdir $temp_storage
fi
if [ ! -d ~/storage ] ; then
	echo "Error - No access to phone storage"
	echo "backups are made to /storage/emulated/0/tel, (this path is also accessible to TEL through ~/storage/shared/tel) if TEL hasn't been granted storage permissions, this will likely fail. Run termux-setup-storage to grant access"
	echo program will exit.. && exit
fi
if [ ! -d ~/storage/shared/tel/backup ] ; then
	mkdir -p $backup_location 
fi
if [ ! -d "$backup_location/$today" ] ; then
	mkdir $backup_location/$today && printf "\e[38;5;2m Backup\e[m%s: created backup folder at: $backup_location/$today \n"
fi
}

make_backup(){
while true
do
	read -p "This will overwrite any previous backups made the same day are you sure you want to continue? y/N : " answer
case $answer in
	[yY]* )
		
		check_folders  #create dirs if missing

		printf "\e[38;5;2m Backup\e[m%s: creating installed pkgs list...\n"
		(apt list --installed > $backup_location/$today/userpkgs.txt > /dev/null 2>&1)
		printf "\e[38;5;2m Backup\e[m%s: backing up configs...\n"
		tar czf $backup_location/$today/userconfs_$backup_name.tar.gz ~/.tel/configs >&/dev/null
		printf "\e[38;5;2m Backup\e[m%s: backing up termux settings...\n"
		tar czf $backup_location/$today/termux_$backup_name.tar.gz ~/.termux >&/dev/null
		printf "\e[38;5;2m Backup\e[m%s: backing up TEL user data...\n"
		tar czf $backup_location/$today/userdata_$backup_name.tar.gz ~/.tel/data >&/dev/null & # last must be child process
		
		#show working spinner
		PID=$!
		i=1
		sp="/-\|"
		echo -n ' '
		while [ -d /proc/$PID ]
		do
			  printf "\b${sp:i++%${#sp}:1}"
			  sleep 0.1
		done
		echo -ne '\r' #remove last spinner
		printf "\e[38;5;2m Backup\e[m%s: completed\n"
		break;;

	[nN]* ) exit;;
	* )     echo "options are y or n...";;
esac
done

}

restore_backup(){
	printf "\e[38;5;2m Restore\e[m%s: loading data...\n"
	cd $backup_location && ls -d | fzf
}

exit_utility(){
	printf "\e[38;5;2m Backup & Restore\e[m%s: Exiting...\n"
	exit 0
}

main() {

printf "\e[38;5;2m Backup & Restore\e[m%s\n"

cmd=(dialog --separate-output --checklist "Backup & Restore options:" 22 76 16)
options=(1 " Backup" 
         2 "勒Restore" 
         3 " Quit")
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            echo "First Option"
	    make_backup
            ;;
        2)
            echo "Second Option"
	    restore_backup
            ;;
        3)
            echo "Third Option"
	    exit_utility
            ;;
        *)
            echo "not an option fool D:"
            ;;
    esac
done
#show menu
#PS3="Enter a number: "
#select option in ' Backup' '勒Restore' ' Quit' ; do
#  case $opt in
#	 Backup)
#		make_backup;;
#	勒Restore)
#		restore_backup;;
#	 Quit)
#		exit_utility;;
#	*)
#		echo "Invalid option $REPLY";;
#  esac
#done
}

main $@

