#!/usr/bin/env bash

if [ "$#" != "0" ]; then
	echo 'usage: tel-restart'
	exit
fi
kill "$(pgrep -f 'status_manager.py')" > /dev/null 2>&1 # cleanup status 
pkill -f 'termux-api' >/dev/null 2>&1
tel-delete-status -1
am broadcast --user 0 \
		 -a com.termux.app.restart com.termux > /dev/null 2>&1
