#!/usr/bin/env bash
# an extremely simple wrapper for casual use of linux package - bc 
if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
	echo -e "Usage: tel-calculator [options] [calculation]
	accepted operations: + - / * ^ 
	tel-calculator -h	= show this help menu
	tel-calculator '5 * 5'	= return answer and exit
	tel-calculator		= prompt user for calculation to perform"
	exit 0
fi
if [ -z "$1" ] ; then
	echo -e "\e[38;5;2m Calculator\e[m: operations [ + - / * ^ % ] ctrl c exits" 
	prev=
	while true
	do
		echo -ne "\e[38;5;2m Calculate\e[m: "
		IFS=''; read -e -i "$prev" input

		prev=$(echo "scale=4; $input" | bc)
		echo -ne "\r\033[K\e[38;5;2m Calculate\e[m: $input = $prev \n"
			done
else
	echo "scale=5; $@" | bc
fi
