#!/usr/bin/env bash
#
##/data/data/com.termux/files/usr/bin/env zsh
# Used to reload TEL
if [ "$THEME_COLS" == "true" ] ; then
	i#[[ -f ~/.cache/wal/sequences ]] && (wal -R -q -e && cat ~/.cache/wal/sequences)
	~/.tel/scripts/apply_color.sh
fi
am broadcast --user 0 -a com.termux.app.reload_style com.termux > /dev/null 2>&1 # reload cols in termux
status_running=$(pgrep -f status_manager.py)
if [ ! -z "$status_running" ] ; then
	~/.tel/scripts/status_manager/toggle_ui.sh
	sleep 0.7	
	~/.tel/scripts/status_manager/toggle_ui.sh &
fi
termux-reload-settings
tmux source-file ~/.tmux.conf
tmux display-message '[TEL] Reloaded!'

