#!/usr/bin/env bash
#cd ~/../ 
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
wallpaper_folder=~/.wallpapers

show_help(){
    printf  "%s\n"\
            "Set a new wallpaper for your device"\
            "tel-wallpaper [OPTIONS] [PATTERN]"\
            "__________________________"\
	    "OPTIONS"\
            "  -h   display this help message"\
            "  -f ~/mywallpaper.jpg  use supplied file"
}
open_url(){
   	if [ -n "$global_url" ]; then
		url=$global_url
	else
		url=$(cat $bookmarks_file | fzf -e --cycle --color=16 --prompt=" Pick a URL to open with an android app:")
	fi
	if [ ! -z $url ] ; then
	termux-open-url $url
	printf "\e[38;5;2m Opening\e[m%s URL: $url" 
	else
		exit 1
	fi
}


if [ -z $1 ] ; then
	cd $wallpaper_folder
	selected_file=$(ls $wallpaper_folder | fzf -e --cycle --color=16 --prompt=" Pick a file to set as your wallpaper:")
	options='-f'
else
	case "$1" in
		-f) #use file
		options=$1
		selected_file=$2
		exit 0
		;;
		-u) #use url
		options=$1
		selected_file=$2
		exit 0
		;;
		# Display the help message
		-h)                                                                        show_help
		exit 0
		;;
 	esac

	file_search="$@"
	selected_file=$(fzf -e --cycle --color=16 --query="$file_search" --prompt=" Open in app: " --select-1)
fi

if [ -z $selected_file ] ; then
#	echo 'No file chosen - Exiting...'
	exit 1
else
	curr_dir=$(pwd)
	printf "\e[38;5;2m Wallpaper\e[m%s Applying: $selected_file: "
	termux-wallpaper $options "$selected_file" || echo "Couldn't find $selected_file"

fi

