#!/usr/bin/env bash
# Open applet for TEL
# Version 0.2
# SealyJ 2020
# requires: fzf fd 
#if not on android also requires: perl-file-mimeinfo

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS="
--info=inline
--multi
--preview-window=up:60%:follow:sharp
--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
--color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008'
--prompt='∼ ' --pointer='>' --marker='✓'
--bind '?:toggle-preview'
--bind 'ctrl-a:select-all'
--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
"
bookmarks_file=~/.tel/data/bookmarks 
global_url=$2
[[ -e $bookmarks_file ]] || (echo 'https://t-e-l.github.io' > ${bookmarks_file} ; echo -n 'https://wiki.termux.com/wiki/Main_Page' >> ${bookmarks_file}) # create new list if none exists)
show_help(){
    printf  "%s\n"\
            "Opens a file or link in external app"\
            "tel-open [OPTIONS] [PATTERN]"\
            "__________________________"\                                              "OPTIONS"\
            "  -h   display this help message"\
            "  -u https://www.github.com  Open github in android browser"\
            "  -u   Open url picker"
}
open_url(){
   	if [ -n "$global_url" ]; then
		url=$global_url
	else
		url=$(cat $bookmarks_file | fzf -e --cycle --color=16 --prompt=" Pick a URL to open with an android app:" --select-1)
	fi
	if [ ! -z $url ] ; then
		if [ $(uname -o) == 'Android' ] ; then
			termux-open-url "$url"
		else
			xdg-open "$url"
		fi	
		printf "\e[38;5;2m Opening\e[m%s URL: $url" 
	else
		exit 1
	fi
}

if [ -z $1 ] ; then
	selected_file=$(fzf --cycle --color=16 --prompt=" Open in app: ")
else
	case "$1" in
		-u) #open url in app instead of file
		open_url
		exit 0
		;;
		# Display the help message
		-h)                                                                        show_help
		exit 0
		;;
 	esac

	file_search="$@"
	selected_file="$(fzf -e --cycle --color=16 --query="$file_search" --prompt=" Open in app: " --select-1)"
fi

if [ -z "$selected_file" ] ; then
#	echo 'No file chosen - Exiting...'
	exit 1
else
	curr_dir=$(pwd)
	printf "\e[38;5;2m Opening\e[m%s file: $curr_dir/$selected_file"

	if [ $(uname -o) == 'Android' ] ; then
		termux-open "$selected_file" || echo "Couldn't open $selected_file"
	else
		mimeopen -n "$selected_file" || echo "Couldn't open $selected_file"
	fi
fi

