#!/usr/bin/env bash
if [ -d /system/app ] && [ -d /system/priv-app ]; then

	read -r os kernel arch <<-EOF
		$(uname -srm)
	EOF
	android_version="Android $(getprop ro.build.version.release)"
	time_zone="$(getprop persist.sys.timezone)"
        kernel="$(uname -r)"
	user_name="$NAME"
	device_model="$(getprop ro.product.device)"
	device_rom="$(getprop ro)"
	device_rooted="$(getprop ro.build.system_root_image)"
	cpu_cores=$(cat /proc/cpuinfo | grep -e 'cpu architecture' | tail -n 1 | cut -d' ' -f3)
	memtotal="$(cat /proc/meminfo | grep -e 'MemTotal' | cut -d' ' -f9)"
	memtotal="$(( memtotal / 1000 )) mB"

	uptime=$(uptime | awk -F'( |,|:)+' '{d=h=m=0; if ($7=="min") m=$6; else {if ($7~/^day/) {d=$6;h=$8;m=$9} else {h=$6;m=$7}}} {print d+0,"days,",h+0,"hrs,",m+0,"mins."}')

	

	
echo """   
                        ▒°		
                        ▒▒▒o             
           ▒▒▒▒▒▒▒▒▒      ▒▒▒o           
         ▒▒▒▒▒▒▒▒▒▒▒▒      ▒▒▒O          
         ▒▒▒▒▒▒▒▒▒▒▒▒▒    ▒▒▒▒0          
    ▒▒▒   ▒▒▒▒▒^▒▒▒^▒▒▒  ▒▒▒▒0▒▒▒▒	 	
 ▄▄▒▒▒▒▒▄▄▄▄▄▒▒▒▒▒▒▒▒▒▄▄▒▒▒▒▒▒▒▒▒▒▒▒  	  User: $user_name  TZ: $time_zone
 ▌  ▒▒▒        ▌          ▒▒▒▒    ▌▒▒	  TEL: $TEL_VERSION  Theme: $TEL_THEME
 ▌▄▄▄▒▒ .;▒▄▄▄▄▌    ▄▄▄▄▄▄o▒▒▒▒   ▌▒▒	  OS: $os $android_version
   ▒▒▌▒▒▒▒ ▌▒▒▒▌    ▌▄▄▄▄▄o▒▒▒▒   ▌0▒▒    Device Codename: $device_model
  ▒▒▒▌     ▌▒▒0▌         o▒▒▒     ▌O▒▒ 	  ROM: $device_rom root: $device_rooted
 ▒▒▒0▌     ▌▒▒O▌    ▄▄▄▄o▒▒▒▒   . ▌o▒▒    Arch: $arch Cpu: $cpu_cores  Mem: $memtotal  
 ▒▒▒O▌ ∙ °▒▌ ▒▒O    ▌▄▄▄▒▒▒▌    ▒o▒▒▒▄▄▄  Kern: $kernel  
  ▒▒▒o▒▒▒▒▒▌  ▒▒o      O▒▒ ▌     ▒▒     ▌ Uptime: $uptime
    ▒▒▒▄▄▄▄▌   ▒▒o▄▄▄▄▄▄▒▒▒▌▄▄▄▄▄▄▄▄▄▄▄▄▌
                ▒▒o      o▒▒  o▒▒       
                ▒o             °▒   
 
"""

else
	echo 'Only made for android'
fi
