#!/usr/bin/env bash
# by @SealyJ - github.com/sealedjoy
version=0.2
hintsfile=~/.tel/help/hints
option="${1}" 
[[ -e $hintsfile ]] || "Hints file missing, recommended to update" > ${hintsfile}  #if no list make a new one
if [ -z "$1" ] ; then
	n=0
	hint_file_lines=()
	IFS=$'\n'
	while read line; 
	do
		#add to array then select
		n=$(( $n + 1 ))
		hint_file_lines+=($line)
	done < $hintsfile
	#select random num from pool
	randomiser=$((RANDOM % $n))
	selected_hint=${hint_file_lines[$randomiser]} #get line at position
	echo "${selected_hint}"

else

	case ${option} in 
		-v | --version)
			printf "\e[33;5;2m Hint\e[m: version: $version"
			exit 0
		;;
		-h | --help)
			echo "tel-hint [OPTION]
		'$> tel-hint'            = give me a hint
		'$> tel-hint -h'         = show this help menu
		'$> tel-hint -v'         = show version info
		'$> tel-hint -a'         = show all hints in list'
		'$> tel-hint -e'         = open hints list in $EDITOR'"
		;; 
		-a | --all)
			cat "$hintsfile"
				;;
		-e | --edit)
			echo "Opening in $EDITOR"
			$EDITOR $hintsfile
			;; 
		*)  
		printf "\e[33;5;2m Hint:\e[munrecognised option"
		exit 1 
		;;
	esac 
fi
