#!/usr/bin/env bash
# Open applet for TEL
# Version 0.2
# SealyJ 2020
# requires: fzf fd 
#if not on android also requires: perl-file-mimeinfo

FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
FZF_DEFAULT_OPTS="
--info=inline
--multi
--preview-window=up:60%:follow:sharp
--preview '([[ -f {} ]] && (termimage --size=35x35 {} || bat --theme=base16 --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
--color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008'
--prompt='∼ ' --pointer='>' --marker='✓'
--bind '?:toggle-preview'
--bind 'ctrl-a:select-all'
--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
"
bookmarks_file=~/.tel/data/bookmarks 
global_url=$2
[[ -e $bookmarks_file ]] || (echo 'https://t-e-l.github.io' > ${bookmarks_file} ; echo -n 'https://wiki.termux.com/wiki/Main_Page' >> ${bookmarks_file}) # create new list if none exists)

files_to_open=()
show_help(){
    printf  "%s\n"\
            "Opens a file or link in external app"\
            "tel-open [OPTIONS] [PATTERN]"\
            "__________________________"\                                             
	    "OPTIONS"\
            "  -h | --help  				Display this help message"\
            "  -u | --url https://www.github.com 	Open github in android browser"\
            "  -u | --url  				Open url picker"
}
open_url(){
   	if [ -n "$global_url" ]; then
		url=$global_url
	else
		url=$(cat $bookmarks_file | fzf -e --cycle --color=16 --prompt=" URL to open in app:" --select-1)
	fi
	if [ ! -z $url ] ; then
		if [ $(uname -o) == 'Android' ] ; then
			termux-open-url "$url"
		else
			xdg-open "$url"
		fi	
		printf "\e[33;5;2m Opening\e[m%s URL: $url" 
	else
		exit 1
	fi
}

if [ -z $1 ] ; then
	selected_files=$(fd --hidden --type f | fzf -m -d -e --cycle --color=16 --prompt="Select (tab key) Open: ")
	IFS=$'\n' read -d '' -r -a files_to_open <<<"$selected_files"
else
	case "$1" in
		-u | --url) #open url in app instead of file
		open_url
		exit 0
		;;
		# Display the help message
		-h | --help)                                                                        show_help
		exit 0
		;;
 	esac

	file_search="$@"
	# allow mutli selection save to array
	selected_files=$(fd --hidden --follow --type f | fzf -m -d -e --cycle -q "$file_search" --color=16 --prompt="Select (tab key) Open: ")
	IFS=$'\n' read -d '' -r -a files_to_open <<<"$selected_files"
fi


if [ -z "${files_to_open}" ] ; then
#	echo 'No files chosen - Exiting...'
	exit 1
else
	curr_dir=$(pwd)
	echo -ne "\n\e[33;5;2m Opening\e[m: "
	for filename in "${files_to_open[@]}"
	do
		echo -ne "$curr_dir/$filename\n"
		if [ $(uname -o) == 'Android' ] ; then
			termux-open "$filename" || echo "Couldn't open $selected_file"
		else
			(mimeopen -n "$filename" > /dev/null 2>&1) > /dev/null & 
			#xdg-open "$selected_file" || echo "Couldn't open $selected_file"
		fi
	done	
fi

