#!/usr/bin/env bash
if [ -d /system/app ] && [ -d /system/priv-app ]; then #check if running on android

	read -r os kernel arch <<-EOF
		$(uname -srm)
	EOF
	android_version="$(getprop ro.build.version.release)"
#	time_zone="$(getprop persist.sys.timezone)"
	device_model="$(getprop ro.product.device)"
	device_rom="$(getprop ro.modversion)"
	device_rooted="$(getprop ro.build.system_root_image)"
	[[ "$device_rooted" == "true" ]] && rooted="root"
	speed_dir="/sys/devices/system/cpu/cpu0/cpufreq"
	cpu_file="/proc/cpuinfo"
	cpu="$(awk -F '\\s*: | @' \
                            '/model name|Hardware|Processor|^cpu model|chip type|^cpu type/ {
                            cpu=$2; if ($1 == "Hardware") exit } END { print cpu }' "$cpu_file")"
	


       # maxspeed="$(< "${speed_dir}/cpuinfo_max_freq")"
       # maxspeed="$((maxspeed / 1000)) MHz"
        speed="$(< "${speed_dir}/scaling_max_freq")" ||\
        speed="$(< "${speed_dir}/cpuinfo_max_freq")"
        speed="$((speed / 1000))MHz"

	
	cores=$(cat /proc/cpuinfo | grep -e 'CPU architecture' | tail -n 1 | cut -d' ' -f3)
	memtotal="$(cat /proc/meminfo | grep -e 'MemTotal' | cut -d' ' -f9)"
	memtotal="$(( memtotal / 1000 )) mB"
	memfree="$(cat /proc/meminfo | grep -e 'MemFree' | cut -d' ' -f11)"
	memfree="$(( memfree / 1000 ))"

	uptime=$(uptime | awk -F'( |,|:)+' '{d=h=m=0; if ($7=="min") m=$6; else {if ($7~/^day/) {d=$6;h=$8;m=$9} else {h=$6;m=$7}}} {print d+0,"days,",h+0,"hrs,",m+0,"min"}')

	

	
echo -ne """   
                        ▒°		
                        ▒▒▒o             
           ▒▒▒▒▒▒▒▒▒      ▒▒▒o           
         ▒▒▒▒▒▒▒▒▒▒▒▒      ▒▒▒O           
         ▒▒▒▒▒▒▒▒▒▒▒▒▒    ▒▒▒▒0          \e[3m\e[1m ${NAME}@${device_model} $time_zone \e[0m
    ▒▒▒   ▒▒▒▒▒^▒▒▒^▒▒▒  ▒▒▒▒0▒▒▒▒	  \e[9m                \e[m
 ▄▄▒▒▒▒▒▄▄▄▄▄▒▒▒▒▒▒▒▒▒▄▄▒▒▒▒▒▒▒▒▒▒▒▒  	 \e[1m os:\e[0m Android $android_version $arch 
 ▌  ▒▒▒        ▌          ▒▒▒▒    ▌▒▒	 \e[1m rom:\e[0m $device_rom 
 ▌▄▄▄▒▒ .;▒▄▄▄▄▌    ▄▄▄▄▄▄o▒▒▒▒   ▌▒▒	 \e[1m kern:\e[0m $kernel 
   ▒▒▌▒▒▒▒ ▌▒▒▒▌    ▌▄▄▄▄▄o▒▒▒▒   ▌0▒▒   \e[1m cpu:\e[0m ($cores) @ $speed 
  ▒▒▒▌     ▌▒▒0▌         o▒▒▒     ▌O▒▒ 	 \e[1m mem:\e[0m $memfree / $memtotal free 
 ▒▒▒0▌     ▌▒▒O▌    ▄▄▄▄o▒▒▒▒   . ▌o▒▒   \e[1m up:\e[0m $uptime      
 ▒▒▒O▌ ∙ °▒▌ ▒▒O    ▌▄▄▄▒▒▒▌    ▒o▒▒▒▄▄▄   
  ▒▒▒o▒▒▒▒▒▌  ▒▒o      O▒▒ ▌     ▒▒     ▌ 
    ▒▒▒▄▄▄▄▌   ▒▒o▄▄▄▄▄▄▒▒▒▌▄▄▄▄▄▄▄▄▄▄▄▄▌ 
                ▒▒o      o▒▒  o▒▒         
                ▒o             °▒   
 
"""

else
	echo 'Only made for android'
fi
