#!/usr/bin/env bash
# Edit applet for TEL
# Version 0.3
# SealyJ 2020
# requires: fzf bat nano 
# optional: magisk su binary
useroot=
[[ -z "$EDITOR" ]] && {
	export EDITOR=nano
	echo 'No $EDITOR set, defaulting to nano'
}
fzf_bin=$(which fzf)
editor=$(which $EDITOR)


if [ "$1" == "-r" ] || [ "$1" == "--root" ] ; then
	shift

	cd / 
	export FZF_DEFAULT_COMMAND='find'
	#useroot='sudo'	
	#selected_file=$(su -s /data/data/com.termux/files/usr/bin/bash -c $fzf_bin)
	#selected_file=$(
	sudo fzf
	echo $?
	#useroot='su --preserve-environment -s /data/data/com.termux/files/usr/bin/zsh -c'
	#search_command='find -not \( -path /sys/kernel/ -prune \) -not \( -path /proc/ -prune \) -not \( -path /mnt/ -prune \) -name \*.js'
	#su --preserve-environment
	sudo $EDITOR $selected_file
	exit 0
else
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS="
--info=inline
--multi
--preview-window=up:60%:follow:sharp
--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
--prompt='∼ ' --pointer='>' --marker='✓'
--bind '?:toggle-preview'
--bind 'ctrl-a:select-all'
--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
"
fi

#--color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008'
show_help(){
    printf  "%s\n"\
            "Opens a file in your terminals text editor"\
            "tel-edit [OPTIONS] [PATTERN]"\
            "__________________________"\                                              "OPTIONS"\
            "  -h   display this help message"\
            "  -r | --root use root privledged"
}


if [ -z $1 ] ; then
	selected_file=$($useroot $fzf_bin --cycle --color=16 --prompt="  Edit with $EDITOR: ")
else
	file_search=$(echo "$@")
	selected_file=$($useroot $fzf_bin --cycle --color=16 --query="$file_search" --prompt="  Edit with $EDITOR: " --select-1)
fi

if [ -z "$selected_file" ] ; then
	# no file selected or cancel fzf selection, this is preferable as it allows user to correct typos in fzf prompt rather than giving 'file not found error' 
	# printf "\e[38;5;2m Edit\e[m%s: Error - file not found "
	exit 1
else
	curr_dir=$(pwd)
	# manipulate history here
	#print -S "$useroot $EDITOR $curr_dir/$selected_file"
	if [ ! -z "$useroot" ] ; then
		printf "\e[38;5;2m Editing\e[m%s file as root: $curr_dir/$selected_file\n"
	else
		printf "\e[38;5;2m Editing\e[m%s file: $curr_dir/$selected_file\n"
	fi
	$useroot $editor "$selected_file"
fi

