#!/usr/bin/env bash
#script for starting / searching youtube with one alias
if [ -z "$YT_PKG_NAME" ] ; then
	YT_PKG_NAME="com.google.android.youtube"
fi
#cat ~/.app_names | grep -e 'NewPipe' > /dev/null 2>&1
#case "$?" in
#	"0" )
#		app_to_use="newpipe"
#		app_name="org.schabi.newpipe"
#		;;
#	*)
#		app_to_use="youtube"
#		app_name="com.google.android.youtube" # /com.google.android.apps.youtube.app.application.Shell$UrlActivity"
#
#		;;
#esac

if [ "$#" == 0 ] ; then #start app if no args
	tel-app "$YT_APP_NAME" > /dev/null 2>&1 
else
	search_term=$@
	[ -z "$*" ] || curl "https://www.youtube.com/results" -s -G --data-urlencode "search_query=$*" | pup 'script' | grep "^ *var ytInitialData" | sed 's/^[^=]*=//g;s/;$//' | jq '..|.videoRenderer?' | sed '/^null$/d' | jq '.title.runs[0].text,.longBylineText.runs[0].text,.shortViewCountText.simpleText,.lengthText.simpleText,.publishedTimeText.simpleText,.videoId'| sed 's/^"//;s/"$//;s/\\"//g' | sed -E -n "s/(.{60}).*/\1/;N;s/\n(.{30}).*/\n\1/;N;N;N;N;s/\n/\t|/g;p" | column -t  -s "$(printf "\t")" | fzf --prompt="Choose a video to play.." --color=16 --delimiter='\|' --nth=1,2  | sed -E 's_.*\|([^|]*)$_https://www.youtube.com/watch?v=\1_' |  xargs -r -I'{}' am start -a android.intent.action.SEND -t text/plain -e android.intent.extra.TEXT {} -p $YT_PKG_NAME > /dev/null 2>&1
	#tel-search -yt "$search_term"
fi
