#!/usr/bin/env bash
#
# TEL caller
#_______________________________________________________________________

# Usage
# call [OPTIONS] [PATTERN]
# call -h
# call -u
# call blah
# call 2121821218

# location of the contacts folder
contactsfile="$HOME/.tel/data/.contacts";


print_ERR_and_die() {
    # Error printing function
    printf "\e[38;5;1m[!]%s\n\e[m"\
           "$*" 1>&2
    exit 1
}

show_help() {
    printf  "%s\n"\
                "call [OPTIONS] [PATTERN]"\
                "__________________________"\
                "OPTIONS"\
		"  -a 'name' 'number'	Add a new contact"\
		"  -d			Display my number"\
                "  -h   		Display this help"\
                "  -u   		Update contact list"
        exit 0
}

update_contacts() {
    # Empty contacts file
    :> "$contactsfile"
    :> ~/.temp
    # move termux-contact-list output to 
    # file descriptor 9
    termux-contact-list > ~/.temp

    # delay for 2 seconds   #what is this for? 
    read -rt "2" <> <(:) || :  

    while IFS=$'\n' read -sr line; do
        [[ ${line} == "  {" ]] && {
            read -r line
            name=${line:9:-2}
            read -r line
            number=${line:11:-1}
            echo "$name | $number" >> "$contactsfile"
        }
    done <~/.temp

    rm ~/.temp
}

add_contact(){
	if [ $# -eq 2 ] ; then
		printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mAdding $2 to contacts %s\n\e[m"
		add_contact_name=$2
		echo 'Contact number:'
		read add_contact_number
	elif [ $# -eq 1 ] ; then
		printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mAdding a new contact %s\n\e[m"
		echo 'Contact name:'
		read add_contact_name
		echo 'Contact number:'
		read add_contact_number
	else
		add_contact_name=$2
		add_contact_number=$3
	fi
	am start -a android.intent.action.INSERT -t vnd.android.cursor.dir/contact -e name $add_contact_name -e phone $add_contact_number > /dev/null 2>&1
	printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mAdded $add_contact_name to contacts%s\n\e[m"
	touch ~/.dialer_flag
	#update_contacts
	exit 0
}


main() {
    
	if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
        	show_help 
	elif [ "$1" == "-a" ] || [ "$1" == "--add" ] ; then
		add_contact "$@"
	fi

    [[ ! -a "$contactsfile" || "$1" == '-u' || -f ~/.dialer_flag ]] && {
	rm -f ~/.dialer_flag
    	printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mGenerating contacts list...%s\n\e[m"
	update_contacts  # if contacts file missing - generate one
        [[ "$1" == '-u' ]] && exit 0
    }

    # fuzzy search in $contactsfile to get the number and
    # name in the format
    # Name | Number
    fzf_output=$(fzf --print-query -e --cycle --color=16 --prompt=" Call: " --query="$*" --select-1 -0 < "$contactsfile")
    IFS=$'\n' read -d '' -r -a selected_contact <<< "$fzf_output"
    case "$?" in
        	# No contact found
        "1"  )
		#fail to get matching contact trying calling number
    		printf  "\e[38;5;2m Calling:\e[m %s\n"\
	    	"[{$selected_contact[0]}"
    		termux-telephony-call ${selected_contact[0]}
    		#printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mContact not found%s\n\e[m"
    		#printf  "\e[38;5;2m Dialer\e[m: \e[38;5;1mContact not found%s\n\e[m"
		exit 1
        ;;

        # If Ctrl+C is used 
        "130")
            return 1
        ;;
esac
    # get the contact's name
    contact_name=$(echo "${selected_contact[1]}" | cut -d "|" -f1) 
    # get the contact's number
    contact_number=$(echo "${selected_contact[1]}" | cut -d "|" -f2 | tr -d '[:space:]')
    printf  "\e[38;5;2m Calling:\e[m %s\n"\
	    "$contact_name[$contact_number]"
    #kills the program if termux-telephony-call command is not available
    ( command -v termux-telephony-call >/dev/null 2>&1 ) || { 
        print_ERR_and_die "termux-telephony-call not available, have you installed termux api?"
    }
    termux-telephony-call "$contact_number"
}

main "$@"
