#!/usr/bin/env bash
#cd ~/../ 
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
wallpaper_folder=~/.wallpapers

show_help(){
    printf  "%s\n"\
            "theme and wallpaper manager"\
            "tel-theme [OPTIONS] [PATTERN]"\
            "__________________________"\
	    "OPTIONS"\
           # "  --install-theme   collect your current theme into a package ready for sharing"\
           # "  --create-theme   collect your current theme into a package ready for sharing"\
            "  -h   display this help message"\
            "  -f ~/mywallpaper.jpg  use supplied file"
}

install_theme(){
	echo 'this is WIP'
}

create_theme(){
	mkdir $TEMP/tel-theme
	cd $TEMP/tel-theme
	cp ~/.tel/configs/theme.conf .
	echo 'this is WIP'
}


if [ -z $1 ] ; then
	cd $wallpaper_folder
	selected_file=$(ls $wallpaper_folder | fzf -e --cycle --color=16 --prompt="Pick a file to theme from:")
	options='-f'
else
	case "$1" in
		-i | --install-theme)
		install_theme
		exit 0
		;;
		-c | --create-theme)
		create_theme
		exit 0
		;;
		-f | --file) #use file
		options=$1
		selected_file=$2
		exit 0
		;;
		-u | --url) #use url
		options=$1
		selected_file=$2
		exit 0
		;;
		# Display the help message
		-h | --help)
		show_help
		exit 0
		;;
 	esac
	file_search="$@"
	selected_file=$(fzf -e --cycle --color=16 --query="$file_search" --prompt="Pick a file to theme from: " --select-1)
	selected_file=$(pwd)/$selected_file
fi

if [ -z $selected_file ] ; then
#	echo 'No file chosen - Exiting...'
	exit 1
else
	curr_dir=$(pwd)
	#wal --preview
	printf "\e[33;5;2m Theme\e[m%s extracting colorscheme from: $selected_file\n"
	wal -i "$selected_file" -n -q -s -t -e || (echo 'failed to get colors from file' ; exit 1)
	#sed -n '4,27p' ~/.cache/wal/colors.sh > ~/.termux/color.properties
	# write to status bar cols
	sed -i '/status-text-color/d' ~/.tel/configs/theme.conf
	fg_text_color=$(sed '8q;d' ~/.cache/wal/colors)
       	echo -e "\nstatus-text-color=$fg_text_color" >> ~/.tel/configs/theme.conf

	printf "\e[33;5;2m Theme\e[m%s setting wallpaper as: $selected_file\n"
	termux-wallpaper $options "$selected_file" || echo "Couldn't find $selected_file"
	~/.tel/scripts/wal_cols_termux.sh # copy wal generated cols to ~/.termux/colors.properties
	am broadcast --user 0 -a com.termux.app.reload_style com.termux > /dev/null 2>&1 # reload cols in termux
	status_running=$(pgrep -f status_manager.py)
	if [ ! -z "$status_running" ] ; then
		~/.tel/scripts/status_manager/toggle_ui.sh
		sleep 0.7	
		~/.tel/scripts/status_manager/toggle_ui.sh
	fi
fi

